<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">signatureBmri</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZyBzdHJpbmdUb1NpZ24gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgInN0
cmluZ1RvU2lnbiIgKTsNClN0cmluZyBrZXlzdG9yZUZpbGUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5n
KCBwaXBlbGluZUN1cnNvciwgImtleXN0b3JlRmlsZSIgKTsNClN0cmluZyBrZXlzdG9yZVBhc3N3
b3JkID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJrZXlzdG9yZVBhc3N3
b3JkIiApOw0KU3RyaW5nIGtleUFsaWFzID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVD
dXJzb3IsICJrZXlBbGlhcyIgKTsNClN0cmluZyBrZXlQYXNzd29yZCA9IElEYXRhVXRpbC5nZXRT
dHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAia2V5UGFzc3dvcmQiICk7DQpTdHJpbmcgYWxnb3JpdGht
ID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJhbGdvcml0aG0iICk7DQoN
CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNCg0KDQpTdHJpbmcgc2lnbmF0dXJlID0gc2lnbihr
ZXlzdG9yZUZpbGUsa2V5c3RvcmVQYXNzd29yZCxrZXlBbGlhcyxrZXlQYXNzd29yZCxhbGdvcml0
aG0sIHN0cmluZ1RvU2lnbik7DQoNCi8vIHBpcGVsaW5lDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1
cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1
cnNvcl8xLCAic2lnbmF0dXJlIiwgc2lnbmF0dXJlICk7DQpwaXBlbGluZUN1cnNvcl8xLmRlc3Ry
b3koKTs=</value>
</Values>
