<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">passwordXMLmasker</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQoJU3RyaW5nCXNlYXJjaFN0cmluZzEgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBl
bGluZUN1cnNvciwgInNlYXJjaFN0cmluZzEiICk7DQoJU3RyaW5nCXNlYXJjaFN0cmluZzIgPSBJ
RGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgInNlYXJjaFN0cmluZzIiICk7DQoJ
U3RyaW5nCWluU3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJp
blN0cmluZyIgKTsNCglTdHJpbmcJcmVwbGFjZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVs
aW5lQ3Vyc29yLCAicmVwbGFjZSIgKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNClN0cmlu
ZyByZXN1bHQgPSBpblN0cmluZzsNCnRyeXsNCkludGVnZXIgc3RyaW5nMVNpemUgPSBzZWFyY2hT
dHJpbmcxLmxlbmd0aCgpOw0KU3RyaW5nIGEgPSBpblN0cmluZzsNCmEgPSBhLnJlcGxhY2UoYS5z
dWJzdHJpbmcoYS5pbmRleE9mKHNlYXJjaFN0cmluZzEpICsgc3RyaW5nMVNpemUsIGEubGFzdElu
ZGV4T2Yoc2VhcmNoU3RyaW5nMikpLCByZXBsYWNlKTsNCnJlc3VsdCA9IGE7DQp9Y2F0Y2ggKEV4
Y2VwdGlvbiBleCkgew0KCQ0KfQ0KLy8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vy
c29yXzEgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vy
c29yXzEsICJyZXN1bHQiLCByZXN1bHQgKTsNCnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOw0K
CQ==</value>
</Values>
